kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-apiserver
  labels:
    app: {{ template "fullname" . }}-apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.apiserver.service.type }}
  selector:
    app: {{ template "fullname" . }}-apiserver
  ports:
  - name: secure
    protocol: TCP
    port: 443
    targetPort: 8443
    {{- if eq .Values.apiserver.service.type "NodePort" }}
    nodePort: {{ .Values.apiserver.service.nodePort.securePort }}
    {{- end }}
