language: go

go:
  - 1.4

env:
 - TEST_ASSETS=true
 - TEST_ASSETS=false

install:
  - ./hack/verify-jsonformat.sh
  - ./hack/install-etcd.sh
  - ./hack/install-std-race.sh
  - ./hack/install-tools.sh
  - ./hack/build-go.sh
  - ./hack/install-assets.sh

script: ./hack/test-assets.sh && PATH=$HOME/gopath/bin:./_output/etcd/bin:$PATH make check-test WHAT="''" TESTFLAGS="-p=4"

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
