language: go

go:
  - 1.4
  - 1.5

env:
  - TEST_ASSETS=true
  - TEST_ASSETS=false

matrix:
  exclude:
  - go: 1.5
    env: TEST_ASSETS=true

install:
  - export PATH=$GOPATH/bin:./third_party/etcd:$PATH
  - make install-travis

script:
  - make check-test TESTFLAGS="-p=4" TESTS="''" # empty quotes are because hack/test-go.sh requires 2 args

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
