language: go

go:
  - 1.6
  - tip

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - make install-travis

script:
  - PERMISSIVE_GO=y make verify

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
