version: 0.1
log:
  level: debug
http:
  addr: :5000
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true
auth:
  openshift: {}
openshift:
  version: 1.0
  auth:
    realm: openshift
    # tokenrealm is a base URL to use for the token-granting registry endpoint.
    # If unspecified, the scheme and host for the token redirect are determined from the incoming request.
    # If specified, a scheme and host must be chosen that all registry clients can resolve and access:
    #
    # tokenrealm: https://example.com:5000
  audit:
    enabled: false
  metrics:
    enabled: false
    # secret is used to authenticate to metrics endpoint. It cannot be empty.
    # Attention! A weak secret can lead to the leakage of private data.
    #
    # secret: TopSecretLongToken
  requests:
    # GET and HEAD requests
    read:
      # maxrunning is a limit for the number of in-flight requests. A zero value means there is no limit.
      maxrunning: 0
      # maxinqueue sets the maximum number of requests that can be queued if the limit for the number of in-flight requests is reached.
      maxinqueue: 0
      # maxwaitinqueue is how long a request can wait in the queue. A zero value means it can wait forever.
      maxwaitinqueue: 0
    # PUT, PATCH, POST, DELETE requests and internal mirroring requests
    write:
      # See description of openshift.requests.read.
      maxrunning: 0
      maxinqueue: 0
      maxwaitinqueue: 0
  quota:
    enabled: false
  cache:
    blobrepositoryttl: 10m
    quotattl: 1m
  pullthrough:
    enabled: true
    mirror: true
  compatibility:
    acceptschema2: true
